// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bank_account.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createBankAccount = `-- name: CreateBankAccount :execresult
INSERT INTO bank_accounts (
    alias,
    last4,
    updated_at_utc
) VALUES (?, ?, ?)
`

type CreateBankAccountParams struct {
	Alias        string `json:"alias"`
	Last4        string `json:"last4"`
	UpdatedAtUtc string `json:"updated_at_utc"`
}

func (q *Queries) CreateBankAccount(ctx context.Context, arg CreateBankAccountParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createBankAccount, arg.Alias, arg.Last4, arg.UpdatedAtUtc)
}

const getActiveBankAccountByID = `-- name: GetActiveBankAccountByID :one
SELECT id, alias, last4, created_at_utc, updated_at_utc, deleted_at_utc
FROM bank_accounts
WHERE id = ? AND deleted_at_utc IS NULL
`

func (q *Queries) GetActiveBankAccountByID(ctx context.Context, id int64) (BankAccount, error) {
	row := q.db.QueryRowContext(ctx, getActiveBankAccountByID, id)
	var i BankAccount
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.Last4,
		&i.CreatedAtUtc,
		&i.UpdatedAtUtc,
		&i.DeletedAtUtc,
	)
	return i, err
}

const getBankAccountByID = `-- name: GetBankAccountByID :one
SELECT id, alias, last4, created_at_utc, updated_at_utc, deleted_at_utc
FROM bank_accounts
WHERE id = ?
`

func (q *Queries) GetBankAccountByID(ctx context.Context, id int64) (BankAccount, error) {
	row := q.db.QueryRowContext(ctx, getBankAccountByID, id)
	var i BankAccount
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.Last4,
		&i.CreatedAtUtc,
		&i.UpdatedAtUtc,
		&i.DeletedAtUtc,
	)
	return i, err
}

const listBalanceAccountLinks = `-- name: ListBalanceAccountLinks :many
SELECT
    l.target,
    l.bank_account_id,
    l.updated_at_utc,
    b.alias AS account_alias,
    b.last4 AS account_last4
FROM balance_account_links l
LEFT JOIN bank_accounts b
    ON b.id = l.bank_account_id
   AND b.deleted_at_utc IS NULL
ORDER BY l.target
`

type ListBalanceAccountLinksRow struct {
	Target        string         `json:"target"`
	BankAccountID sql.NullInt64  `json:"bank_account_id"`
	UpdatedAtUtc  string         `json:"updated_at_utc"`
	AccountAlias  sql.NullString `json:"account_alias"`
	AccountLast4  sql.NullString `json:"account_last4"`
}

func (q *Queries) ListBalanceAccountLinks(ctx context.Context) ([]ListBalanceAccountLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, listBalanceAccountLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBalanceAccountLinksRow
	for rows.Next() {
		var i ListBalanceAccountLinksRow
		if err := rows.Scan(
			&i.Target,
			&i.BankAccountID,
			&i.UpdatedAtUtc,
			&i.AccountAlias,
			&i.AccountLast4,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBankAccounts = `-- name: ListBankAccounts :many
SELECT id, alias, last4, created_at_utc, updated_at_utc, deleted_at_utc
FROM bank_accounts
WHERE (?1 = 1 OR deleted_at_utc IS NULL)
ORDER BY lower(alias), id
`

func (q *Queries) ListBankAccounts(ctx context.Context, includeDeleted interface{}) ([]BankAccount, error) {
	rows, err := q.db.QueryContext(ctx, listBankAccounts, includeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankAccount
	for rows.Next() {
		var i BankAccount
		if err := rows.Scan(
			&i.ID,
			&i.Alias,
			&i.Last4,
			&i.CreatedAtUtc,
			&i.UpdatedAtUtc,
			&i.DeletedAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchActiveBankAccountsByLookup = `-- name: SearchActiveBankAccountsByLookup :many
SELECT id, alias, last4, created_at_utc, updated_at_utc, deleted_at_utc
FROM bank_accounts
WHERE deleted_at_utc IS NULL
  AND (
      instr(lower(alias), lower(?1)) > 0
      OR instr(last4, ?1) > 0
  )
ORDER BY lower(alias), id
LIMIT ?2
`

type SearchActiveBankAccountsByLookupParams struct {
	LookupText string `json:"lookup_text"`
	LimitRows  int64  `json:"limit_rows"`
}

func (q *Queries) SearchActiveBankAccountsByLookup(ctx context.Context, arg SearchActiveBankAccountsByLookupParams) ([]BankAccount, error) {
	rows, err := q.db.QueryContext(ctx, searchActiveBankAccountsByLookup, arg.LookupText, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankAccount
	for rows.Next() {
		var i BankAccount
		if err := rows.Scan(
			&i.ID,
			&i.Alias,
			&i.Last4,
			&i.CreatedAtUtc,
			&i.UpdatedAtUtc,
			&i.DeletedAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteBankAccount = `-- name: SoftDeleteBankAccount :execresult
UPDATE bank_accounts
SET deleted_at_utc = ?, updated_at_utc = ?
WHERE id = ? AND deleted_at_utc IS NULL
`

type SoftDeleteBankAccountParams struct {
	DeletedAtUtc sql.NullString `json:"deleted_at_utc"`
	UpdatedAtUtc string         `json:"updated_at_utc"`
	ID           int64          `json:"id"`
}

func (q *Queries) SoftDeleteBankAccount(ctx context.Context, arg SoftDeleteBankAccountParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, softDeleteBankAccount, arg.DeletedAtUtc, arg.UpdatedAtUtc, arg.ID)
}

const updateBankAccountByID = `-- name: UpdateBankAccountByID :execresult
UPDATE bank_accounts
SET alias = CASE
    WHEN ?1 = 1 THEN ?2
    ELSE alias
END,
    last4 = CASE
    WHEN ?3 = 1 THEN ?4
    ELSE last4
END,
    updated_at_utc = ?5
WHERE id = ?6
  AND deleted_at_utc IS NULL
`

type UpdateBankAccountByIDParams struct {
	SetAlias     interface{} `json:"set_alias"`
	Alias        string      `json:"alias"`
	SetLast4     interface{} `json:"set_last4"`
	Last4        string      `json:"last4"`
	UpdatedAtUtc string      `json:"updated_at_utc"`
	ID           int64       `json:"id"`
}

func (q *Queries) UpdateBankAccountByID(ctx context.Context, arg UpdateBankAccountByIDParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateBankAccountByID,
		arg.SetAlias,
		arg.Alias,
		arg.SetLast4,
		arg.Last4,
		arg.UpdatedAtUtc,
		arg.ID,
	)
}

const upsertBalanceAccountLink = `-- name: UpsertBalanceAccountLink :execresult
INSERT INTO balance_account_links (
    target,
    bank_account_id,
    updated_at_utc
) VALUES (?1, ?2, ?3)
ON CONFLICT(target) DO UPDATE SET
    bank_account_id = excluded.bank_account_id,
    updated_at_utc = excluded.updated_at_utc
`

type UpsertBalanceAccountLinkParams struct {
	Target        string        `json:"target"`
	BankAccountID sql.NullInt64 `json:"bank_account_id"`
	UpdatedAtUtc  string        `json:"updated_at_utc"`
}

func (q *Queries) UpsertBalanceAccountLink(ctx context.Context, arg UpsertBalanceAccountLinkParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, upsertBalanceAccountLink, arg.Target, arg.BankAccountID, arg.UpdatedAtUtc)
}
