// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cap.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createMonthlyCap = `-- name: CreateMonthlyCap :execresult
INSERT INTO monthly_caps (
    month_key,
    amount_minor,
    currency_code,
    updated_at_utc
) VALUES (?, ?, ?, ?)
`

type CreateMonthlyCapParams struct {
	MonthKey     string `json:"month_key"`
	AmountMinor  int64  `json:"amount_minor"`
	CurrencyCode string `json:"currency_code"`
	UpdatedAtUtc string `json:"updated_at_utc"`
}

func (q *Queries) CreateMonthlyCap(ctx context.Context, arg CreateMonthlyCapParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMonthlyCap,
		arg.MonthKey,
		arg.AmountMinor,
		arg.CurrencyCode,
		arg.UpdatedAtUtc,
	)
}

const createMonthlyCapChange = `-- name: CreateMonthlyCapChange :execresult
INSERT INTO monthly_cap_changes (
    month_key,
    old_amount_minor,
    new_amount_minor,
    currency_code,
    changed_at_utc
) VALUES (?, ?, ?, ?, ?)
`

type CreateMonthlyCapChangeParams struct {
	MonthKey       string        `json:"month_key"`
	OldAmountMinor sql.NullInt64 `json:"old_amount_minor"`
	NewAmountMinor int64         `json:"new_amount_minor"`
	CurrencyCode   string        `json:"currency_code"`
	ChangedAtUtc   string        `json:"changed_at_utc"`
}

func (q *Queries) CreateMonthlyCapChange(ctx context.Context, arg CreateMonthlyCapChangeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMonthlyCapChange,
		arg.MonthKey,
		arg.OldAmountMinor,
		arg.NewAmountMinor,
		arg.CurrencyCode,
		arg.ChangedAtUtc,
	)
}

const getMonthlyCapByMonthKey = `-- name: GetMonthlyCapByMonthKey :one
SELECT id, month_key, amount_minor, currency_code, created_at_utc, updated_at_utc
FROM monthly_caps
WHERE month_key = ?
`

func (q *Queries) GetMonthlyCapByMonthKey(ctx context.Context, monthKey string) (MonthlyCap, error) {
	row := q.db.QueryRowContext(ctx, getMonthlyCapByMonthKey, monthKey)
	var i MonthlyCap
	err := row.Scan(
		&i.ID,
		&i.MonthKey,
		&i.AmountMinor,
		&i.CurrencyCode,
		&i.CreatedAtUtc,
		&i.UpdatedAtUtc,
	)
	return i, err
}

const listMonthlyCapChangesByMonthKey = `-- name: ListMonthlyCapChangesByMonthKey :many
SELECT id, month_key, old_amount_minor, new_amount_minor, currency_code, changed_at_utc
FROM monthly_cap_changes
WHERE month_key = ?
ORDER BY changed_at_utc, id
`

func (q *Queries) ListMonthlyCapChangesByMonthKey(ctx context.Context, monthKey string) ([]MonthlyCapChange, error) {
	rows, err := q.db.QueryContext(ctx, listMonthlyCapChangesByMonthKey, monthKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonthlyCapChange
	for rows.Next() {
		var i MonthlyCapChange
		if err := rows.Scan(
			&i.ID,
			&i.MonthKey,
			&i.OldAmountMinor,
			&i.NewAmountMinor,
			&i.CurrencyCode,
			&i.ChangedAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumActiveExpensesByMonthAndCurrency = `-- name: SumActiveExpensesByMonthAndCurrency :one
SELECT CAST(COALESCE(SUM(amount_minor), 0) AS INTEGER) AS total_amount_minor
FROM transactions
WHERE type = 'expense'
  AND deleted_at_utc IS NULL
  AND currency_code = ?
  AND transaction_date_utc >= ?
  AND transaction_date_utc < ?
`

type SumActiveExpensesByMonthAndCurrencyParams struct {
	CurrencyCode         string `json:"currency_code"`
	TransactionDateUtc   string `json:"transaction_date_utc"`
	TransactionDateUtc_2 string `json:"transaction_date_utc_2"`
}

func (q *Queries) SumActiveExpensesByMonthAndCurrency(ctx context.Context, arg SumActiveExpensesByMonthAndCurrencyParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumActiveExpensesByMonthAndCurrency, arg.CurrencyCode, arg.TransactionDateUtc, arg.TransactionDateUtc_2)
	var total_amount_minor int64
	err := row.Scan(&total_amount_minor)
	return total_amount_minor, err
}

const updateMonthlyCapByMonthKey = `-- name: UpdateMonthlyCapByMonthKey :execresult
UPDATE monthly_caps
SET amount_minor = ?, currency_code = ?, updated_at_utc = ?
WHERE month_key = ?
`

type UpdateMonthlyCapByMonthKeyParams struct {
	AmountMinor  int64  `json:"amount_minor"`
	CurrencyCode string `json:"currency_code"`
	UpdatedAtUtc string `json:"updated_at_utc"`
	MonthKey     string `json:"month_key"`
}

func (q *Queries) UpdateMonthlyCapByMonthKey(ctx context.Context, arg UpdateMonthlyCapByMonthKeyParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateMonthlyCapByMonthKey,
		arg.AmountMinor,
		arg.CurrencyCode,
		arg.UpdatedAtUtc,
		arg.MonthKey,
	)
}
