// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createCategory = `-- name: CreateCategory :execresult
INSERT INTO categories (name) VALUES (?)
`

func (q *Queries) CreateCategory(ctx context.Context, name string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCategory, name)
}

const getActiveCategoryByID = `-- name: GetActiveCategoryByID :one
SELECT id, name, created_at_utc, updated_at_utc
FROM categories
WHERE id = ? AND deleted_at_utc IS NULL
`

type GetActiveCategoryByIDRow struct {
	ID           int64  `json:"id"`
	Name         string `json:"name"`
	CreatedAtUtc string `json:"created_at_utc"`
	UpdatedAtUtc string `json:"updated_at_utc"`
}

func (q *Queries) GetActiveCategoryByID(ctx context.Context, id int64) (GetActiveCategoryByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveCategoryByID, id)
	var i GetActiveCategoryByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAtUtc,
		&i.UpdatedAtUtc,
	)
	return i, err
}

const listActiveCategories = `-- name: ListActiveCategories :many
SELECT id, name, created_at_utc, updated_at_utc
FROM categories
WHERE deleted_at_utc IS NULL
ORDER BY lower(name), id
`

type ListActiveCategoriesRow struct {
	ID           int64  `json:"id"`
	Name         string `json:"name"`
	CreatedAtUtc string `json:"created_at_utc"`
	UpdatedAtUtc string `json:"updated_at_utc"`
}

func (q *Queries) ListActiveCategories(ctx context.Context) ([]ListActiveCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveCategoriesRow
	for rows.Next() {
		var i ListActiveCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAtUtc,
			&i.UpdatedAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orphanActiveTransactionsByCategoryID = `-- name: OrphanActiveTransactionsByCategoryID :execresult
UPDATE transactions
SET category_id = NULL, updated_at_utc = ?
WHERE category_id = ? AND deleted_at_utc IS NULL
`

type OrphanActiveTransactionsByCategoryIDParams struct {
	UpdatedAtUtc string        `json:"updated_at_utc"`
	CategoryID   sql.NullInt64 `json:"category_id"`
}

func (q *Queries) OrphanActiveTransactionsByCategoryID(ctx context.Context, arg OrphanActiveTransactionsByCategoryIDParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, orphanActiveTransactionsByCategoryID, arg.UpdatedAtUtc, arg.CategoryID)
}

const renameActiveCategory = `-- name: RenameActiveCategory :execresult
UPDATE categories
SET name = ?, updated_at_utc = ?
WHERE id = ? AND deleted_at_utc IS NULL
`

type RenameActiveCategoryParams struct {
	Name         string `json:"name"`
	UpdatedAtUtc string `json:"updated_at_utc"`
	ID           int64  `json:"id"`
}

func (q *Queries) RenameActiveCategory(ctx context.Context, arg RenameActiveCategoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, renameActiveCategory, arg.Name, arg.UpdatedAtUtc, arg.ID)
}

const softDeleteCategory = `-- name: SoftDeleteCategory :execresult
UPDATE categories
SET deleted_at_utc = ?, updated_at_utc = ?
WHERE id = ? AND deleted_at_utc IS NULL
`

type SoftDeleteCategoryParams struct {
	DeletedAtUtc sql.NullString `json:"deleted_at_utc"`
	UpdatedAtUtc string         `json:"updated_at_utc"`
	ID           int64          `json:"id"`
}

func (q *Queries) SoftDeleteCategory(ctx context.Context, arg SoftDeleteCategoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, softDeleteCategory, arg.DeletedAtUtc, arg.UpdatedAtUtc, arg.ID)
}
