// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fx.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createFXRateSnapshot = `-- name: CreateFXRateSnapshot :execresult
INSERT INTO fx_rate_snapshots (
    provider,
    base_currency,
    quote_currency,
    rate,
    rate_date,
    is_estimate,
    fetched_at_utc
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateFXRateSnapshotParams struct {
	Provider      string `json:"provider"`
	BaseCurrency  string `json:"base_currency"`
	QuoteCurrency string `json:"quote_currency"`
	Rate          string `json:"rate"`
	RateDate      string `json:"rate_date"`
	IsEstimate    int64  `json:"is_estimate"`
	FetchedAtUtc  string `json:"fetched_at_utc"`
}

func (q *Queries) CreateFXRateSnapshot(ctx context.Context, arg CreateFXRateSnapshotParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createFXRateSnapshot,
		arg.Provider,
		arg.BaseCurrency,
		arg.QuoteCurrency,
		arg.Rate,
		arg.RateDate,
		arg.IsEstimate,
		arg.FetchedAtUtc,
	)
}

const getFXRateSnapshotByKey = `-- name: GetFXRateSnapshotByKey :one
SELECT id,
       provider,
       base_currency,
       quote_currency,
       rate,
       rate_date,
       is_estimate,
       fetched_at_utc
FROM fx_rate_snapshots
WHERE provider = ?
  AND base_currency = ?
  AND quote_currency = ?
  AND rate_date = ?
  AND is_estimate = ?
`

type GetFXRateSnapshotByKeyParams struct {
	Provider      string `json:"provider"`
	BaseCurrency  string `json:"base_currency"`
	QuoteCurrency string `json:"quote_currency"`
	RateDate      string `json:"rate_date"`
	IsEstimate    int64  `json:"is_estimate"`
}

func (q *Queries) GetFXRateSnapshotByKey(ctx context.Context, arg GetFXRateSnapshotByKeyParams) (FxRateSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getFXRateSnapshotByKey,
		arg.Provider,
		arg.BaseCurrency,
		arg.QuoteCurrency,
		arg.RateDate,
		arg.IsEstimate,
	)
	var i FxRateSnapshot
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.BaseCurrency,
		&i.QuoteCurrency,
		&i.Rate,
		&i.RateDate,
		&i.IsEstimate,
		&i.FetchedAtUtc,
	)
	return i, err
}
