// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: label.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createLabel = `-- name: CreateLabel :execresult
INSERT INTO labels (name) VALUES (?)
`

func (q *Queries) CreateLabel(ctx context.Context, name string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createLabel, name)
}

const getActiveLabelByID = `-- name: GetActiveLabelByID :one
SELECT id, name, created_at_utc, updated_at_utc, deleted_at_utc
FROM labels
WHERE id = ? AND deleted_at_utc IS NULL
`

func (q *Queries) GetActiveLabelByID(ctx context.Context, id int64) (Label, error) {
	row := q.db.QueryRowContext(ctx, getActiveLabelByID, id)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAtUtc,
		&i.UpdatedAtUtc,
		&i.DeletedAtUtc,
	)
	return i, err
}

const listActiveLabels = `-- name: ListActiveLabels :many
SELECT id, name, created_at_utc, updated_at_utc, deleted_at_utc
FROM labels
WHERE deleted_at_utc IS NULL
ORDER BY lower(name), id
`

func (q *Queries) ListActiveLabels(ctx context.Context) ([]Label, error) {
	rows, err := q.db.QueryContext(ctx, listActiveLabels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAtUtc,
			&i.UpdatedAtUtc,
			&i.DeletedAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameActiveLabel = `-- name: RenameActiveLabel :execresult
UPDATE labels
SET name = ?, updated_at_utc = ?
WHERE id = ? AND deleted_at_utc IS NULL
`

type RenameActiveLabelParams struct {
	Name         string `json:"name"`
	UpdatedAtUtc string `json:"updated_at_utc"`
	ID           int64  `json:"id"`
}

func (q *Queries) RenameActiveLabel(ctx context.Context, arg RenameActiveLabelParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, renameActiveLabel, arg.Name, arg.UpdatedAtUtc, arg.ID)
}

const softDeleteLabel = `-- name: SoftDeleteLabel :execresult
UPDATE labels
SET deleted_at_utc = ?, updated_at_utc = ?
WHERE id = ? AND deleted_at_utc IS NULL
`

type SoftDeleteLabelParams struct {
	DeletedAtUtc sql.NullString `json:"deleted_at_utc"`
	UpdatedAtUtc string         `json:"updated_at_utc"`
	ID           int64          `json:"id"`
}

func (q *Queries) SoftDeleteLabel(ctx context.Context, arg SoftDeleteLabelParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, softDeleteLabel, arg.DeletedAtUtc, arg.UpdatedAtUtc, arg.ID)
}

const softDeleteTransactionLabelLinksByLabelID = `-- name: SoftDeleteTransactionLabelLinksByLabelID :execresult
UPDATE transaction_labels
SET deleted_at_utc = ?
WHERE label_id = ? AND deleted_at_utc IS NULL
`

type SoftDeleteTransactionLabelLinksByLabelIDParams struct {
	DeletedAtUtc sql.NullString `json:"deleted_at_utc"`
	LabelID      int64          `json:"label_id"`
}

func (q *Queries) SoftDeleteTransactionLabelLinksByLabelID(ctx context.Context, arg SoftDeleteTransactionLabelLinksByLabelIDParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, softDeleteTransactionLabelLinksByLabelID, arg.DeletedAtUtc, arg.LabelID)
}
