// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type AuditEvent struct {
	ID           int64          `json:"id"`
	Action       string         `json:"action"`
	EntityType   string         `json:"entity_type"`
	EntityID     string         `json:"entity_id"`
	Source       string         `json:"source"`
	PayloadJson  sql.NullString `json:"payload_json"`
	CreatedAtUtc string         `json:"created_at_utc"`
}

type Category struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	CreatedAtUtc string         `json:"created_at_utc"`
	UpdatedAtUtc string         `json:"updated_at_utc"`
	DeletedAtUtc sql.NullString `json:"deleted_at_utc"`
}

type FxRateSnapshot struct {
	ID            int64  `json:"id"`
	Provider      string `json:"provider"`
	BaseCurrency  string `json:"base_currency"`
	QuoteCurrency string `json:"quote_currency"`
	Rate          string `json:"rate"`
	RateDate      string `json:"rate_date"`
	IsEstimate    int64  `json:"is_estimate"`
	FetchedAtUtc  string `json:"fetched_at_utc"`
}

type Label struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	CreatedAtUtc string         `json:"created_at_utc"`
	UpdatedAtUtc string         `json:"updated_at_utc"`
	DeletedAtUtc sql.NullString `json:"deleted_at_utc"`
}

type MonthlyCap struct {
	ID           int64  `json:"id"`
	MonthKey     string `json:"month_key"`
	AmountMinor  int64  `json:"amount_minor"`
	CurrencyCode string `json:"currency_code"`
	CreatedAtUtc string `json:"created_at_utc"`
	UpdatedAtUtc string `json:"updated_at_utc"`
}

type MonthlyCapChange struct {
	ID             int64         `json:"id"`
	MonthKey       string        `json:"month_key"`
	OldAmountMinor sql.NullInt64 `json:"old_amount_minor"`
	NewAmountMinor int64         `json:"new_amount_minor"`
	CurrencyCode   string        `json:"currency_code"`
	ChangedAtUtc   string        `json:"changed_at_utc"`
}

type Setting struct {
	ID                         int64          `json:"id"`
	DefaultCurrencyCode        string         `json:"default_currency_code"`
	DisplayTimezone            string         `json:"display_timezone"`
	OrphanCountThreshold       int64          `json:"orphan_count_threshold"`
	OrphanSpendingThresholdBps int64          `json:"orphan_spending_threshold_bps"`
	OnboardingCompletedAtUtc   sql.NullString `json:"onboarding_completed_at_utc"`
	CreatedAtUtc               string         `json:"created_at_utc"`
	UpdatedAtUtc               string         `json:"updated_at_utc"`
}

type Transaction struct {
	ID                 int64          `json:"id"`
	Type               string         `json:"type"`
	AmountMinor        int64          `json:"amount_minor"`
	CurrencyCode       string         `json:"currency_code"`
	TransactionDateUtc string         `json:"transaction_date_utc"`
	CategoryID         sql.NullInt64  `json:"category_id"`
	Note               sql.NullString `json:"note"`
	CreatedAtUtc       string         `json:"created_at_utc"`
	UpdatedAtUtc       string         `json:"updated_at_utc"`
	DeletedAtUtc       sql.NullString `json:"deleted_at_utc"`
}

type TransactionLabel struct {
	ID            int64          `json:"id"`
	TransactionID int64          `json:"transaction_id"`
	LabelID       int64          `json:"label_id"`
	CreatedAtUtc  string         `json:"created_at_utc"`
	DeletedAtUtc  sql.NullString `json:"deleted_at_utc"`
}
