// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type AuditEvent struct {
	ID           int64          `json:"id"`
	Action       string         `json:"action"`
	EntityType   string         `json:"entity_type"`
	EntityID     string         `json:"entity_id"`
	Source       string         `json:"source"`
	PayloadJson  sql.NullString `json:"payload_json"`
	CreatedAtUtc string         `json:"created_at_utc"`
}

type BalanceAccountLink struct {
	Target        string        `json:"target"`
	BankAccountID sql.NullInt64 `json:"bank_account_id"`
	UpdatedAtUtc  string        `json:"updated_at_utc"`
}

type BankAccount struct {
	ID           int64          `json:"id"`
	Alias        string         `json:"alias"`
	Last4        string         `json:"last4"`
	CreatedAtUtc string         `json:"created_at_utc"`
	UpdatedAtUtc string         `json:"updated_at_utc"`
	DeletedAtUtc sql.NullString `json:"deleted_at_utc"`
}

type Card struct {
	ID           int64          `json:"id"`
	Nickname     string         `json:"nickname"`
	Description  sql.NullString `json:"description"`
	Last4        string         `json:"last4"`
	Brand        string         `json:"brand"`
	CardType     string         `json:"card_type"`
	DueDay       sql.NullInt64  `json:"due_day"`
	CreatedAtUtc string         `json:"created_at_utc"`
	UpdatedAtUtc string         `json:"updated_at_utc"`
	DeletedAtUtc sql.NullString `json:"deleted_at_utc"`
}

type Category struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	CreatedAtUtc string         `json:"created_at_utc"`
	UpdatedAtUtc string         `json:"updated_at_utc"`
	DeletedAtUtc sql.NullString `json:"deleted_at_utc"`
}

type CreditLiabilityEvent struct {
	ID                     int64          `json:"id"`
	CardID                 int64          `json:"card_id"`
	CurrencyCode           string         `json:"currency_code"`
	EventType              string         `json:"event_type"`
	AmountMinorSigned      int64          `json:"amount_minor_signed"`
	ReferenceTransactionID sql.NullInt64  `json:"reference_transaction_id"`
	Note                   sql.NullString `json:"note"`
	CreatedAtUtc           string         `json:"created_at_utc"`
}

type FxRateSnapshot struct {
	ID            int64  `json:"id"`
	Provider      string `json:"provider"`
	BaseCurrency  string `json:"base_currency"`
	QuoteCurrency string `json:"quote_currency"`
	Rate          string `json:"rate"`
	RateDate      string `json:"rate_date"`
	IsEstimate    int64  `json:"is_estimate"`
	FetchedAtUtc  string `json:"fetched_at_utc"`
}

type Label struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	CreatedAtUtc string         `json:"created_at_utc"`
	UpdatedAtUtc string         `json:"updated_at_utc"`
	DeletedAtUtc sql.NullString `json:"deleted_at_utc"`
}

type MonthlyCap struct {
	ID           int64  `json:"id"`
	MonthKey     string `json:"month_key"`
	AmountMinor  int64  `json:"amount_minor"`
	CurrencyCode string `json:"currency_code"`
	CreatedAtUtc string `json:"created_at_utc"`
	UpdatedAtUtc string `json:"updated_at_utc"`
}

type MonthlyCapChange struct {
	ID             int64         `json:"id"`
	MonthKey       string        `json:"month_key"`
	OldAmountMinor sql.NullInt64 `json:"old_amount_minor"`
	NewAmountMinor int64         `json:"new_amount_minor"`
	CurrencyCode   string        `json:"currency_code"`
	ChangedAtUtc   string        `json:"changed_at_utc"`
}

type SavingsEvent struct {
	ID                       int64          `json:"id"`
	EventType                string         `json:"event_type"`
	AmountMinor              int64          `json:"amount_minor"`
	CurrencyCode             string         `json:"currency_code"`
	EventDateUtc             string         `json:"event_date_utc"`
	SourceBankAccountID      sql.NullInt64  `json:"source_bank_account_id"`
	DestinationBankAccountID sql.NullInt64  `json:"destination_bank_account_id"`
	Note                     sql.NullString `json:"note"`
	CreatedAtUtc             string         `json:"created_at_utc"`
}

type ScheduledPayment struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	AmountMinor   int64          `json:"amount_minor"`
	CurrencyCode  string         `json:"currency_code"`
	DayOfMonth    int64          `json:"day_of_month"`
	StartMonthKey string         `json:"start_month_key"`
	EndMonthKey   sql.NullString `json:"end_month_key"`
	CategoryID    sql.NullInt64  `json:"category_id"`
	Note          sql.NullString `json:"note"`
	CreatedAtUtc  string         `json:"created_at_utc"`
	UpdatedAtUtc  string         `json:"updated_at_utc"`
	DeletedAtUtc  sql.NullString `json:"deleted_at_utc"`
}

type ScheduledPaymentExecution struct {
	ID           int64         `json:"id"`
	ScheduleID   int64         `json:"schedule_id"`
	MonthKey     string        `json:"month_key"`
	EntryID      sql.NullInt64 `json:"entry_id"`
	CreatedAtUtc string        `json:"created_at_utc"`
}

type Setting struct {
	ID                         int64          `json:"id"`
	DefaultCurrencyCode        string         `json:"default_currency_code"`
	DisplayTimezone            string         `json:"display_timezone"`
	OrphanCountThreshold       int64          `json:"orphan_count_threshold"`
	OrphanSpendingThresholdBps int64          `json:"orphan_spending_threshold_bps"`
	OnboardingCompletedAtUtc   sql.NullString `json:"onboarding_completed_at_utc"`
	CreatedAtUtc               string         `json:"created_at_utc"`
	UpdatedAtUtc               string         `json:"updated_at_utc"`
}

type Transaction struct {
	ID                 int64          `json:"id"`
	Type               string         `json:"type"`
	AmountMinor        int64          `json:"amount_minor"`
	CurrencyCode       string         `json:"currency_code"`
	TransactionDateUtc string         `json:"transaction_date_utc"`
	CategoryID         sql.NullInt64  `json:"category_id"`
	BankAccountID      sql.NullInt64  `json:"bank_account_id"`
	Note               sql.NullString `json:"note"`
	CreatedAtUtc       string         `json:"created_at_utc"`
	UpdatedAtUtc       string         `json:"updated_at_utc"`
	DeletedAtUtc       sql.NullString `json:"deleted_at_utc"`
}

type TransactionLabel struct {
	ID            int64          `json:"id"`
	TransactionID int64          `json:"transaction_id"`
	LabelID       int64          `json:"label_id"`
	CreatedAtUtc  string         `json:"created_at_utc"`
	DeletedAtUtc  sql.NullString `json:"deleted_at_utc"`
}

type TransactionPaymentMethod struct {
	TransactionID int64         `json:"transaction_id"`
	MethodType    string        `json:"method_type"`
	CardID        sql.NullInt64 `json:"card_id"`
	CreatedAtUtc  string        `json:"created_at_utc"`
	UpdatedAtUtc  string        `json:"updated_at_utc"`
}
