// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: savings.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createSavingsEvent = `-- name: CreateSavingsEvent :execresult
INSERT INTO savings_events (
    event_type,
    amount_minor,
    currency_code,
    event_date_utc,
    note
) VALUES (?, ?, ?, ?, ?)
`

type CreateSavingsEventParams struct {
	EventType    string         `json:"event_type"`
	AmountMinor  int64          `json:"amount_minor"`
	CurrencyCode string         `json:"currency_code"`
	EventDateUtc string         `json:"event_date_utc"`
	Note         sql.NullString `json:"note"`
}

func (q *Queries) CreateSavingsEvent(ctx context.Context, arg CreateSavingsEventParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSavingsEvent,
		arg.EventType,
		arg.AmountMinor,
		arg.CurrencyCode,
		arg.EventDateUtc,
		arg.Note,
	)
}

const listSavingsEvents = `-- name: ListSavingsEvents :many
SELECT id, event_type, amount_minor, currency_code, event_date_utc, note, created_at_utc
FROM savings_events
WHERE (?1 IS NULL OR event_date_utc >= ?1)
  AND (?2 IS NULL OR event_date_utc <= ?2)
  AND (?3 IS NULL OR event_type = ?3)
ORDER BY event_date_utc, id
`

type ListSavingsEventsParams struct {
	DateFromUtc interface{} `json:"date_from_utc"`
	DateToUtc   interface{} `json:"date_to_utc"`
	EventType   interface{} `json:"event_type"`
}

func (q *Queries) ListSavingsEvents(ctx context.Context, arg ListSavingsEventsParams) ([]SavingsEvent, error) {
	rows, err := q.db.QueryContext(ctx, listSavingsEvents, arg.DateFromUtc, arg.DateToUtc, arg.EventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SavingsEvent
	for rows.Next() {
		var i SavingsEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AmountMinor,
			&i.CurrencyCode,
			&i.EventDateUtc,
			&i.Note,
			&i.CreatedAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
