// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: schedule.sql

package sqlc

import (
	"context"
	"database/sql"
)

const attachScheduledPaymentExecutionEntry = `-- name: AttachScheduledPaymentExecutionEntry :execresult
UPDATE scheduled_payment_executions
SET entry_id = ?
WHERE schedule_id = ? AND month_key = ?
`

type AttachScheduledPaymentExecutionEntryParams struct {
	EntryID    sql.NullInt64 `json:"entry_id"`
	ScheduleID int64         `json:"schedule_id"`
	MonthKey   string        `json:"month_key"`
}

func (q *Queries) AttachScheduledPaymentExecutionEntry(ctx context.Context, arg AttachScheduledPaymentExecutionEntryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, attachScheduledPaymentExecutionEntry, arg.EntryID, arg.ScheduleID, arg.MonthKey)
}

const claimScheduledPaymentExecution = `-- name: ClaimScheduledPaymentExecution :execresult
INSERT INTO scheduled_payment_executions (
    schedule_id,
    month_key,
    created_at_utc
) VALUES (?, ?, ?)
`

type ClaimScheduledPaymentExecutionParams struct {
	ScheduleID   int64  `json:"schedule_id"`
	MonthKey     string `json:"month_key"`
	CreatedAtUtc string `json:"created_at_utc"`
}

func (q *Queries) ClaimScheduledPaymentExecution(ctx context.Context, arg ClaimScheduledPaymentExecutionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, claimScheduledPaymentExecution, arg.ScheduleID, arg.MonthKey, arg.CreatedAtUtc)
}

const createScheduledPayment = `-- name: CreateScheduledPayment :execresult
INSERT INTO scheduled_payments (
    name,
    amount_minor,
    currency_code,
    day_of_month,
    start_month_key,
    end_month_key,
    category_id,
    note,
    updated_at_utc
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateScheduledPaymentParams struct {
	Name          string         `json:"name"`
	AmountMinor   int64          `json:"amount_minor"`
	CurrencyCode  string         `json:"currency_code"`
	DayOfMonth    int64          `json:"day_of_month"`
	StartMonthKey string         `json:"start_month_key"`
	EndMonthKey   sql.NullString `json:"end_month_key"`
	CategoryID    sql.NullInt64  `json:"category_id"`
	Note          sql.NullString `json:"note"`
	UpdatedAtUtc  string         `json:"updated_at_utc"`
}

func (q *Queries) CreateScheduledPayment(ctx context.Context, arg CreateScheduledPaymentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createScheduledPayment,
		arg.Name,
		arg.AmountMinor,
		arg.CurrencyCode,
		arg.DayOfMonth,
		arg.StartMonthKey,
		arg.EndMonthKey,
		arg.CategoryID,
		arg.Note,
		arg.UpdatedAtUtc,
	)
}

const getActiveScheduledPaymentByID = `-- name: GetActiveScheduledPaymentByID :one
SELECT id, name, amount_minor, currency_code, day_of_month, start_month_key, end_month_key, category_id, note, created_at_utc, updated_at_utc, deleted_at_utc
FROM scheduled_payments
WHERE id = ? AND deleted_at_utc IS NULL
`

func (q *Queries) GetActiveScheduledPaymentByID(ctx context.Context, id int64) (ScheduledPayment, error) {
	row := q.db.QueryRowContext(ctx, getActiveScheduledPaymentByID, id)
	var i ScheduledPayment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AmountMinor,
		&i.CurrencyCode,
		&i.DayOfMonth,
		&i.StartMonthKey,
		&i.EndMonthKey,
		&i.CategoryID,
		&i.Note,
		&i.CreatedAtUtc,
		&i.UpdatedAtUtc,
		&i.DeletedAtUtc,
	)
	return i, err
}

const listScheduledPaymentExecutions = `-- name: ListScheduledPaymentExecutions :many
SELECT id, schedule_id, month_key, entry_id, created_at_utc
FROM scheduled_payment_executions
ORDER BY schedule_id, month_key, id
`

func (q *Queries) ListScheduledPaymentExecutions(ctx context.Context) ([]ScheduledPaymentExecution, error) {
	rows, err := q.db.QueryContext(ctx, listScheduledPaymentExecutions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledPaymentExecution
	for rows.Next() {
		var i ScheduledPaymentExecution
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.MonthKey,
			&i.EntryID,
			&i.CreatedAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledPaymentExecutionsByScheduleID = `-- name: ListScheduledPaymentExecutionsByScheduleID :many
SELECT id, schedule_id, month_key, entry_id, created_at_utc
FROM scheduled_payment_executions
WHERE schedule_id = ?
ORDER BY month_key, id
`

func (q *Queries) ListScheduledPaymentExecutionsByScheduleID(ctx context.Context, scheduleID int64) ([]ScheduledPaymentExecution, error) {
	rows, err := q.db.QueryContext(ctx, listScheduledPaymentExecutionsByScheduleID, scheduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledPaymentExecution
	for rows.Next() {
		var i ScheduledPaymentExecution
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.MonthKey,
			&i.EntryID,
			&i.CreatedAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledPayments = `-- name: ListScheduledPayments :many
SELECT
    sp.id,
    sp.name,
    sp.amount_minor,
    sp.currency_code,
    sp.day_of_month,
    sp.start_month_key,
    sp.end_month_key,
    sp.category_id,
    sp.note,
    sp.created_at_utc,
    sp.updated_at_utc,
    sp.deleted_at_utc,
    (
        SELECT MAX(spe.month_key)
        FROM scheduled_payment_executions spe
        WHERE spe.schedule_id = sp.id
    ) AS last_executed_month_key
FROM scheduled_payments sp
WHERE (?1 = 1 OR sp.deleted_at_utc IS NULL)
ORDER BY lower(sp.name), sp.id
`

type ListScheduledPaymentsRow struct {
	ID                   int64          `json:"id"`
	Name                 string         `json:"name"`
	AmountMinor          int64          `json:"amount_minor"`
	CurrencyCode         string         `json:"currency_code"`
	DayOfMonth           int64          `json:"day_of_month"`
	StartMonthKey        string         `json:"start_month_key"`
	EndMonthKey          sql.NullString `json:"end_month_key"`
	CategoryID           sql.NullInt64  `json:"category_id"`
	Note                 sql.NullString `json:"note"`
	CreatedAtUtc         string         `json:"created_at_utc"`
	UpdatedAtUtc         string         `json:"updated_at_utc"`
	DeletedAtUtc         sql.NullString `json:"deleted_at_utc"`
	LastExecutedMonthKey interface{}    `json:"last_executed_month_key"`
}

func (q *Queries) ListScheduledPayments(ctx context.Context, includeDeleted interface{}) ([]ListScheduledPaymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listScheduledPayments, includeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScheduledPaymentsRow
	for rows.Next() {
		var i ListScheduledPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AmountMinor,
			&i.CurrencyCode,
			&i.DayOfMonth,
			&i.StartMonthKey,
			&i.EndMonthKey,
			&i.CategoryID,
			&i.Note,
			&i.CreatedAtUtc,
			&i.UpdatedAtUtc,
			&i.DeletedAtUtc,
			&i.LastExecutedMonthKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteScheduledPayment = `-- name: SoftDeleteScheduledPayment :execresult
UPDATE scheduled_payments
SET deleted_at_utc = ?, updated_at_utc = ?
WHERE id = ? AND deleted_at_utc IS NULL
`

type SoftDeleteScheduledPaymentParams struct {
	DeletedAtUtc sql.NullString `json:"deleted_at_utc"`
	UpdatedAtUtc string         `json:"updated_at_utc"`
	ID           int64          `json:"id"`
}

func (q *Queries) SoftDeleteScheduledPayment(ctx context.Context, arg SoftDeleteScheduledPaymentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, softDeleteScheduledPayment, arg.DeletedAtUtc, arg.UpdatedAtUtc, arg.ID)
}
