// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getSettings = `-- name: GetSettings :one
SELECT id,
       default_currency_code,
       display_timezone,
       orphan_count_threshold,
       orphan_spending_threshold_bps,
       onboarding_completed_at_utc,
       created_at_utc,
       updated_at_utc
FROM settings
WHERE id = 1
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.DefaultCurrencyCode,
		&i.DisplayTimezone,
		&i.OrphanCountThreshold,
		&i.OrphanSpendingThresholdBps,
		&i.OnboardingCompletedAtUtc,
		&i.CreatedAtUtc,
		&i.UpdatedAtUtc,
	)
	return i, err
}

const upsertSettings = `-- name: UpsertSettings :execresult
INSERT INTO settings (
    id,
    default_currency_code,
    display_timezone,
    orphan_count_threshold,
    orphan_spending_threshold_bps,
    onboarding_completed_at_utc,
    updated_at_utc
) VALUES (1, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    default_currency_code = excluded.default_currency_code,
    display_timezone = excluded.display_timezone,
    orphan_count_threshold = excluded.orphan_count_threshold,
    orphan_spending_threshold_bps = excluded.orphan_spending_threshold_bps,
    onboarding_completed_at_utc = excluded.onboarding_completed_at_utc,
    updated_at_utc = excluded.updated_at_utc
`

type UpsertSettingsParams struct {
	DefaultCurrencyCode        string         `json:"default_currency_code"`
	DisplayTimezone            string         `json:"display_timezone"`
	OrphanCountThreshold       int64          `json:"orphan_count_threshold"`
	OrphanSpendingThresholdBps int64          `json:"orphan_spending_threshold_bps"`
	OnboardingCompletedAtUtc   sql.NullString `json:"onboarding_completed_at_utc"`
	UpdatedAtUtc               string         `json:"updated_at_utc"`
}

func (q *Queries) UpsertSettings(ctx context.Context, arg UpsertSettingsParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, upsertSettings,
		arg.DefaultCurrencyCode,
		arg.DisplayTimezone,
		arg.OrphanCountThreshold,
		arg.OrphanSpendingThresholdBps,
		arg.OnboardingCompletedAtUtc,
		arg.UpdatedAtUtc,
	)
}
